#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/sbin/accel-pppd
CONF=/etc/accel-ppp.conf

start_service() {
	[ -f "$CONF" ] || {
		echo "accel-ppp: config $CONF not found, copying dist config"
		cp /etc/accel-ppp.conf.dist "$CONF"
	}

	procd_open_instance
	procd_set_param command "$PROG" -c "$CONF" -p /var/run/accel-ppp.pid -d
	procd_set_param respawn
	procd_set_param file "$CONF"
	procd_close_instance
}

reload_service() {
	procd_send_signal accel-ppp
}
