FROM ubuntu:24.04
	# We start from the ubuntu base

    # Arguments we can take
    ARG radiusdesk_volume

    ## Install all software required

    # Set up required language pack
    RUN apt-get update
    RUN apt-get -y install language-pack-en-base
	
	# Install, enable & configure Nginx & FPM
	RUN apt-get -y install nginx
	COPY ./default /etc/nginx/sites-enabled/
	
	RUN apt-get -y install php-fpm
	RUN apt-get -y install php-cli php-mysql php-gd php-curl php-xml php-mbstring php-intl php-sqlite3 git wget

    # Install Freeradius
    RUN apt-get -y install libdatetime-perl
	RUN apt-get -y install libdbd-mysql-perl
	RUN apt-get -y install libdigest-hmac-perl
	RUN apt-get -y install libdatetime-format-rfc3339-perl
	RUN apt-get -y install eapoltest
    RUN apt-get -y install freeradius freeradius-mysql
	RUN apt-get -y install libjson-perl libwww-perl

    # Install supervisord to start up all services - as docker only allows one process to start up
    RUN apt-get install -y supervisor

    # Prepare all directories
    
    COPY ./disable_strict_mode.cnf /etc/mysql/conf.d/
    COPY ./rdcore /var/www/rdcore

    RUN mkdir -p /var/www/html
    RUN ln -s /var/www/rdcore/rd /var/www/html/rd
    RUN ln -s /var/www/rdcore/cake4 /var/www/html/cake4
    #If backward compatibility is required for older firmware of MESHdesk
    RUN ln -s /var/www/rdcore/cake4 /var/www/html/cake3
    RUN ln -s /var/www/rdcore/login /var/www/html/login
    RUN ln -s /var/www/rdcore/AmpConf/build/production/AmpConf /var/www/html/conf_dev
    RUN ln -s /var/www/rdcore/login/rd_client/build/production/AmpConf /var/www/html/usage
    RUN ln -s /var/www/rdcore/cake4/rd_cake/setup/scripts/reporting /var/www/html/reporting
    
    # Create requried directories
    RUN mkdir -p /var/www/html/cake4/rd_cake/logs
    RUN mkdir -p /var/www/html/cake4/rd_cake/webroot/files/imagecache
    RUN mkdir -p /var/www/html/cake4/rd_cake/tmp
    
    # Set permissions
    RUN chown -R www-data. /var/www/html/cake4/rd_cake/tmp
    RUN chown -R www-data. /var/www/html/cake4/rd_cake/logs
    RUN chown -R www-data. /var/www/html/cake4/rd_cake/webroot/img/realms
    RUN chown -R www-data. /var/www/html/cake4/rd_cake/webroot/img/dynamic_details
    RUN chown -R www-data. /var/www/html/cake4/rd_cake/webroot/img/dynamic_photos
    RUN chown -R www-data. /var/www/html/cake4/rd_cake/webroot/img/access_providers
    RUN chown -R www-data. /var/www/html/cake4/rd_cake/webroot/img/hardwares
    RUN chown -R www-data. /var/www/html/cake4/rd_cake/webroot/files/imagecache

    ## General startup script with database init and freeradius start
    #COPY ./startup.sh /

    # Setup Cron jobs
	RUN apt-get install -y cron
    RUN cp /var/www/html/cake4/rd_cake/setup/cron/cron4 /etc/cron.d/
    RUN chmod 0644 /etc/cron.d/cron4
    RUN crontab /etc/cron.d/cron4

    # configure php-fpm
    RUN mkdir -p /var/log/php-fpm
  
    # Sets up Nginx with php-fpm and required php plugins

	## configure freeradius

    RUN mv /etc/freeradius /etc/freeradius.orig
    RUN mkdir -p /etc/freeradius
	RUN cp -R /var/www/html/cake4/rd_cake/setup/radius/freeradius /etc/freeradius
    
	# Set freeradius permissions
	RUN chown -R freerad: /etc/freeradius/3.0/
	RUN chown freerad:www-data /etc/freeradius
	RUN chown freerad:www-data /etc/freeradius/3.0
	RUN chown freerad:www-data /etc/freeradius/3.0/dictionary

    #RUN mkdir -p  /var/log/freeradius
    RUN mkdir -p /var/run/freeradius
    RUN chown freerad: /var/run/freeradius

    COPY ./freeradius.service /lib/systemd/system/

    ## cleanup
    RUN rm -rf /var/lib/apt/lists/*

    # supervisord allows multiple processes to be started with a single process
    COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

    # Copy php settings
    COPY ./php.ini /etc/php/php.ini

    # Fix all cake4 configs to point to external database
    RUN sed  -i  "s/'host' => 'localhost'/'host' => 'rdmariadb'/g" /var/www/html/cake4/rd_cake/config/app_local.php
    RUN sed -i "s/\$servername = \"localhost\";/\$servername = \"rdmariadb\";/g" /var/www/rdcore/cake4/rd_cake/setup/scripts/reporting/*.php

    # Fix all Freeradius configs to point to our new database
    RUN sed -i 's/server = "localhost"/server = "rdmariadb"/g' /etc/freeradius/3.0/mods-available/sql
	RUN sed -i "s/\$conf{'db_host'}\s*=\s*\"127.0.0.1\";/\$conf{'db_host'} = \"rdmariadb\";/g" /etc/freeradius/3.0/mods-config/perl/*.pl

    # Copy files from production to root www
    RUN cp -R /var/www/html/rd/build/production/Rd/* /var/www/html/

    # entrypoint run script when container starts - ignores what is in command
    ENTRYPOINT /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

    # Expose radiusDESK front end ports
    EXPOSE 80/tcp
    EXPOSE 1812/udp
    EXPOSE 1813/udp



