Ext.define('Rd.model.mFinAuthorizeNetTransaction', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'id',           		type: 'int'     },
        {name: 'user',         		type: 'string'  },
        {name: 'user_id',      		type: 'int'  },
        {name: 'voucher_name', 		type: 'string'  },
        {name: 'voucher_id',   		type: 'int'  },
        {name: 'top_up_id',    		type: 'int'  },      
		{name: 'description',  		type: 'string'  },
		{name: 'x_response_code',   type: 'int'  },
		{name: 'x_response_subcode',   		type: 'int'  },
		{name: 'x_response_reason_code',   	type: 'int'  },
		{name: 'x_response_reason_text',   	type: 'string'  },
		{name: 'x_auth_code',   type: 'string'  },
		{name: 'x_avs_code',   	type: 'string'  },
		{name: 'x_trans_id',   	type: 'string'  },
		{name: 'x_auth_code',   type: 'string'  },
		{name: 'x_method',   	type: 'string'  },
		{name: 'x_card_type',   type: 'string'  },
		{name: 'x_account_number',   	type: 'string'  },
		{name: 'x_first_name', 	type: 'string'  },
		{name: 'x_last_name',   type: 'string'  },
		{name: 'x_company',   	type: 'string'  },
		{name: 'x_address',   	type: 'string'  },
		{name: 'x_city',   		type: 'string'  },
		{name: 'x_state', 		type: 'string'  },
		{name: 'x_zip',   		type: 'string'  },
		{name: 'x_country',   	type: 'string'  },
		{name: 'x_phone',   	type: 'string'  },
		{name: 'x_fax', 		type: 'string'  },
		{name: 'x_email',   	type: 'string'  },
		{name: 'x_amount',   	type: 'string'  },
		{name: 'x_catalog_link_id', 	type: 'string'  },
        {name: 'created',      type: 'date',       dateFormat: 'Y-m-d H:i:s'   },
        {name: 'modified',     type: 'date',       dateFormat: 'Y-m-d H:i:s'   },
        {name: 'tag',          type: 'string'   },
        {name: 'notes',        type: 'bool'},
        {name: 'update',       type: 'bool'},
        {name: 'delete',       type: 'bool'}
        ]
});

